link:
  thingscloud:
    freeswitch:
      esl:
        inbound:
          defaultPassword: ClueCon
          performance: false
          performanceCostTime: 200
          servers:
            - host: 192.168.10.112
              port: 8021
              timeoutSeconds: 5
            - host: 192.168.10.114
              port: 8021
              timeoutSeconds: 5
          events:
            - all
#logging:
#  level:
#    link: DEBUG
